variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  tags:
    - docker
  image: registry.gitlab.com/tarantool/enterprise/central:latest

  before_script:
    - yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    - yum -y install make cmake gcc g++ git openssl python36u python36u-pip npm
    - pip3.6 install -r pytest/requirements.txt
    - tarantoolctl rocks make
  script:
    - pytest -v
    - ./taptest.lua
