stages:
 - build

build:
  stage: build
  variables:
    ADMIN_UI_VERSION: "test"
  tags:
   - shell
  artifacts:
    untracked: true
    paths:
      - tarantool-enterprise-admin-ui.tar.gz
  script:
   - make

